package amitsimplyfiedtutorial.com.Ostream;
import java.util.Date;
import java.util.stream.Stream;

public class StreamBuilders4 {
	 
	public static void main(String[] args) {
		Stream<Date> stream = Stream.generate(() -> {
			return new Date();
		});
		stream.forEach(p -> System.out.println(p));
	}
}
/*
	Returns an infinite sequential unordered stream where each element is generated by the provided Supplier. 
	This is suitable for generating constant streams, streams of random elements, etc.

*/
